name: testtest11
version: 55
cron:
- url: /diming.php
  schedule: "@midnight"
- url: /diming2.php
  schedule: "0 1 * * *"
- url: /diming3.php
  schedule: "0 2 * * *"
- url: /diming4.php
  schedule: "0 3 * * *"
- url: /diming5.php
  schedule: "0 4 * * *"
- url: /diming6.php
  schedule: "0 5 * * *"
- url: /diming7.php
  schedule: "0 6 * * *"
- url: /diming8.php
  schedule: "0 7 * * *"
- url: /diming9.php
  schedule: "0 8 * * *"
- url: /diming10.php
  schedule: "0 9 * * *"
