name: testtest11
version: 55
cron:
- url: /diming.php
  schedule: "@midnight"
- url: /diming2.php
  schedule: "*/30 * * * *"
- url: /diming3.php
  schedule: "*/30 * * * *"
- url: /diming4.php
  schedule: "*/30 * * * *"
- url: /diming5.php
  schedule: "*/30 * * * *"
- url: /diming6.php
  schedule: "*/30 * * * *"
- url: /diming7.php
  schedule: "*/30 * * * *"
- url: /diming8.php
  schedule: "*/30 * * * *"
- url: /diming9.php
  schedule: "*/30 * * * *"
- url: /diming10.php
  schedule: "*/30 * * * *"
